version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.11
    commands:
      - echo "Starting build..."

  pre_build:
    commands:
      - echo "Detecting project type..."
      - |
        if [ -f "package.json" ]; then
          echo "Node.js project detected"
          npm install
        elif [ -f "requirements.txt" ]; then
          echo "Python project detected"
          pip install -r requirements.txt
        else
          echo "Static website detected"
        fi

  build:
    commands:
      - echo "Building project..."
      - |
        if [ -f "package.json" ] && grep -q '"build"' package.json; then
          npm run build || echo "No build script"
        fi

  post_build:
    commands:
      - echo "Adding CodeDeploy files..."
      - |
        cat > appspec.yml << 'APPSPEC'
        version: 0.0
        os: linux
        files:
          - source: /
            destination: /var/www/html
        hooks:
          BeforeInstall:
            - location: scripts/before_install.sh
              timeout: 300
              runas: root
          AfterInstall:
            - location: scripts/after_install.sh
              timeout: 300
              runas: root
          ApplicationStart:
            - location: scripts/start_application.sh
              timeout: 300
              runas: root
          ValidateService:
            - location: scripts/validate_service.sh
              timeout: 300
              runas: root
        APPSPEC
      - mkdir -p scripts
      - |
        cat > scripts/before_install.sh << 'SCRIPT'
        #!/bin/bash
        echo "=== before_install.sh ==="
        sudo yum install -y httpd
        sudo systemctl stop httpd || true
        sudo rm -rf /var/www/html/*
        echo "=== done ==="
        SCRIPT
      - |
        cat > scripts/after_install.sh << 'SCRIPT'
        #!/bin/bash
        echo "=== after_install.sh ==="
        cd /var/www/html
        if [ -d "build" ]; then cp -r build/* .; fi
        if [ -d "dist" ]; then cp -r dist/* .; fi
        sudo chown -R apache:apache /var/www/html
        sudo chmod -R 755 /var/www/html
        echo "=== done ==="
        SCRIPT
      - |
        cat > scripts/start_application.sh << 'SCRIPT'
        #!/bin/bash
        echo "=== start_application.sh ==="
        sudo systemctl start httpd
        sudo systemctl enable httpd
        echo "=== done ==="
        SCRIPT
      - |
        cat > scripts/validate_service.sh << 'SCRIPT'
        #!/bin/bash
        echo "=== validate_service.sh ==="
        if sudo systemctl is-active --quiet httpd; then
            echo "Apache is running!"
            exit 0
        else
            echo "Apache failed"
            exit 1
        fi
        SCRIPT
      - chmod +x scripts/*.sh
      - echo "Build completed!"

artifacts:
  files:
    - '**/*'