version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.11
    commands:
      - echo "Starting build..."

  pre_build:
    commands:
      - |
        if [ -f "package.json" ]; then
          echo "Node.js project detected"
          npm install
        elif [ -f "requirements.txt" ]; then
          echo "Python project detected"
          pip install -r requirements.txt
        else
          echo "Static website detected"
        fi

  build:
    commands:
      - |
        if [ -f "package.json" ] && grep -q '"build"' package.json; then
          npm run build || echo "No build script"
        fi

  post_build:
    commands:
      - mkdir -p scripts
      - |
        cat > appspec.yml << 'EOF'
        version: 0.0
        os: linux
        files:
          - source: /
            destination: /usr/share/nginx/html
        hooks:
          BeforeInstall:
            - location: scripts/before_install.sh
              timeout: 300
              runas: root
          AfterInstall:
            - location: scripts/after_install.sh
              timeout: 300
              runas: root
          ApplicationStart:
            - location: scripts/start_application.sh
              timeout: 300
              runas: root
          ValidateService:
            - location: scripts/validate_service.sh
              timeout: 300
              runas: root
        EOF
      - |
        cat > scripts/before_install.sh << 'EOF'
        #!/bin/bash
        yum install -y nginx
        systemctl stop nginx || true
        rm -rf /usr/share/nginx/html/*
        EOF
      - |
        cat > scripts/after_install.sh << 'EOF'
        #!/bin/bash
        cd /usr/share/nginx/html
        if [ -d "build" ]; then cp -r build/* .; fi
        if [ -d "dist" ]; then cp -r dist/* .; fi
        chown -R nginx:nginx /usr/share/nginx/html
        chmod -R 755 /usr/share/nginx/html
        EOF
      - |
        cat > scripts/start_application.sh << 'EOF'
        #!/bin/bash
        systemctl start nginx
        systemctl enable nginx
        EOF
      - |
        cat > scripts/validate_service.sh << 'EOF'
        #!/bin/bash
        systemctl is-active --quiet nginx && exit 0 || exit 1
        EOF
      - chmod +x scripts/*.sh

artifacts:
  files:
    - '**/*'